### ISSUE TITLE
coredump in lua-mongoc-collection.c:236

### ISSUE THREAD

**Issue by bhhbazinga** [mongodb-labs/mongorover#81]
#0  0x0000000000003ac6 in ?? ()
#1  0x00007f4e1ba944ea in lua_mongo_collection_update (L=0x7f4e223e1c68)
    at /home/bhhbazinga/gdmj_engine/3rd/mongorover/c_wrapper/lua-mongoc-collection.c:236
#2  0x00000000004139b4 in luaD_precall (L=0x7f4e223e1c68, func=0x7f4e12c685f0, nresults=1) at ldo.c:434
#3  0x000000000041fa77 in luaV_execute (L=0x7f4e223e1c68) at lvm.c:1146
#4  0x0000000000413c7f in luaD_call (L=0x7f4e223e1c68, func=<optimized out>, nResults=<optimized out>)
    at ldo.c:499
#5  0x000000000041129a in lua_pcallk (L=L@entry=0x7f4e223e1c68, nargs=nargs@entry=1, nresults=nresults@entry=-1, 
    errfunc=errfunc@entry=2, ctx=ctx@entry=2, k=k@entry=0x427510 <finishpcall>) at lapi.c:981
#6  0x00000000004275d0 in luaB_xpcall (L=0x7f4e223e1c68) at lbaselib.c:441
#7  0x00000000004139b4 in luaD_precall (L=0x7f4e223e1c68, func=0x7f4e12c68450, nresults=0) at ldo.c:434
#8  0x000000000041fa77 in luaV_execute (L=0x7f4e223e1c68) at lvm.c:1146
#9  0x0000000000413c7f in luaD_call (L=0x7f4e223e1c68, func=<optimized out>, nResults=<optimized out>)
    at ldo.c:499
#10 0x000000000041129a in lua_pcallk (L=L@entry=0x7f4e223e1c68, nargs=nargs@entry=2, nresults=nresults@entry=-1, 
    errfunc=errfunc@entry=2, ctx=ctx@entry=2, k=k@entry=0x427510 <finishpcall>) at lapi.c:981
#11 0x00000000004275d0 in luaB_xpcall (L=0x7f4e223e1c68) at lbaselib.c:441
#12 0x00000000004139b4 in luaD_precall (L=0x7f4e223e1c68, func=0x7f4e12c68130, nresults=-1) at ldo.c:434
#13 0x000000000041fa77 in luaV_execute (L=0x7f4e223e1c68) at lvm.c:1146
#14 0x0000000000413730 in unroll (L=0x7f4e223e1c68, ud=<optimized out>) at ldo.c:556
#15 0x00000000004130e2 in luaD_rawrunprotected (L=L@entry=0x7f4e223e1c68, f=f@entry=0x413b80 <resume>, 
    ud=ud@entry=0x7f4e249f275c) at ldo.c:142
#16 0x0000000000413da1 in lua_resume (L=L@entry=0x7f4e223e1c68, from=from@entry=0x7f4e2103f608, 
    nargs=nargs@entry=6) at ldo.c:664
#17 0x0000000000428514 in auxresume (L=L@entry=0x7f4e2103f608, co=co@entry=0x7f4e223e1c68, narg=6)
    at lcorolib.c:39
#18 0x0000000000428851 in luaB_coresume (L=0x7f4e2103f608) at lcorolib.c:60
#19 0x00000000004139b4 in luaD_precall (L=0x7f4e2103f608, func=0x7f4e14224270, nresults=-1) at ldo.c:434
#20 0x000000000041fa77 in luaV_execute (L=0x7f4e2103f608) at lvm.c:1146
#21 0x0000000000413c7f in luaD_call (L=L@entry=0x7f4e2103f608, func=<optimized out>, nResults=<optimized out>)
    at ldo.c:499

**Comment by christopherjwang** [comment]
Do you have code that will reproduce this issue?
